### PR TITLE
Make paths and end lines platform independent

### PR DESCRIPTION
**Pull request by joekiller**
I think this helps with #100 and #82

### CODE REVIEW

**Comment by joekiller** [comment]
PS h264 support

Seems like h264 only writes to the tf folder as well

**Comment by joekiller** [comment]
Added webm and native StartTF2 support.

webm has the same problem where the movie folder must be the same as the tf folder.

**Comment by joekiller** [comment]
Almost got osx done. Maybe tonight...

**Comment by quanticc** [comment]
Looking forward to merge this, let me know when it's ready. Thanks!

**Comment by joekiller** [comment]
@quanticc works in OSX now. This PR is done for now. Happy thanksgiving!

**Comment by joekiller** [comment]
Rebased, squashed a commit, and fixed a typo.

**Comment by quanticc** [comment]
Thanks joe for the help! This will be available on the preview channel for people using the launcher, while I get more feedback to close #100

**Pull request merged**
